package com.example.alarm_jinxuan.utils

import com.example.alarm_jinxuan.model.WorldClockEntity

object WorldClockUtils {
    private val HOT_CITIES = listOf(
        // 【亚洲：180个】
        // 中国（40个）
        "北京" to "Beijing" to "Asia/Shanghai" to "+08:00",
        "上海" to "Shanghai" to "Asia/Shanghai" to "+08:00",
        "广州" to "Guangzhou" to "Asia/Shanghai" to "+08:00",
        "深圳" to "Shenzhen" to "Asia/Shanghai" to "+08:00",
        "重庆" to "Chongqing" to "Asia/Shanghai" to "+08:00",
        "成都" to "Chengdu" to "Asia/Shanghai" to "+08:00",
        "杭州" to "Hangzhou" to "Asia/Shanghai" to "+08:00",
        "武汉" to "Wuhan" to "Asia/Shanghai" to "+08:00",
        "南京" to "Nanjing" to "Asia/Shanghai" to "+08:00",
        "西安" to "Xi'an" to "Asia/Shanghai" to "+08:00",
        "天津" to "Tianjin" to "Asia/Shanghai" to "+08:00",
        "苏州" to "Suzhou" to "Asia/Shanghai" to "+08:00",
        "郑州" to "Zhengzhou" to "Asia/Shanghai" to "+08:00",
        "长沙" to "Changsha" to "Asia/Shanghai" to "+08:00",
        "青岛" to "Qingdao" to "Asia/Shanghai" to "+08:00",
        "宁波" to "Ningbo" to "Asia/Shanghai" to "+08:00",
        "沈阳" to "Shenyang" to "Asia/Shanghai" to "+08:00",
        "合肥" to "Hefei" to "Asia/Shanghai" to "+08:00",
        "厦门" to "Xiamen" to "Asia/Shanghai" to "+08:00",
        "福州" to "Fuzhou" to "Asia/Shanghai" to "+08:00",
        "无锡" to "Wuxi" to "Asia/Shanghai" to "+08:00",
        "济南" to "Jinan" to "Asia/Shanghai" to "+08:00",
        "大连" to "Dalian" to "Asia/Shanghai" to "+08:00",
        "昆明" to "Kunming" to "Asia/Shanghai" to "+08:00",
        "哈尔滨" to "Harbin" to "Asia/Shanghai" to "+08:00",
        "长春" to "Changchun" to "Asia/Shanghai" to "+08:00",
        "石家庄" to "Shijiazhuang" to "Asia/Shanghai" to "+08:00",
        "南宁" to "Nanning" to "Asia/Shanghai" to "+08:00",
        "泉州" to "Quanzhou" to "Asia/Shanghai" to "+08:00",
        "温州" to "Wenzhou" to "Asia/Shanghai" to "+08:00",
        "佛山" to "Foshan" to "Asia/Shanghai" to "+08:00",
        "东莞" to "Dongguan" to "Asia/Shanghai" to "+08:00",
        "唐山" to "Tangshan" to "Asia/Shanghai" to "+08:00",
        "烟台" to "Yantai" to "Asia/Shanghai" to "+08:00",
        "常州" to "Changzhou" to "Asia/Shanghai" to "+08:00",
        "徐州" to "Xuzhou" to "Asia/Shanghai" to "+08:00",
        "潍坊" to "Weifang" to "Asia/Shanghai" to "+08:00",
        "绍兴" to "Shaoxing" to "Asia/Shanghai" to "+08:00",
        "南通" to "Nantong" to "Asia/Shanghai" to "+08:00",
        "嘉兴" to "Jiaxing" to "Asia/Shanghai" to "+08:00",
        "香港" to "Hong Kong" to "Asia/Hong_Kong" to "+08:00",
        "台北" to "Taipei" to "Asia/Taipei" to "+08:00",
        "高雄" to "Kaohsiung" to "Asia/Taipei" to "+08:00",

        // 日本（10个）
        "东京" to "Tokyo" to "Asia/Tokyo" to "+09:00",
        "大阪" to "Osaka" to "Asia/Tokyo" to "+09:00",
        "横滨" to "Yokohama" to "Asia/Tokyo" to "+09:00",
        "名古屋" to "Nagoya" to "Asia/Tokyo" to "+09:00",
        "神户" to "Kobe" to "Asia/Tokyo" to "+09:00",
        "京都" to "Kyoto" to "Asia/Tokyo" to "+09:00",
        "福冈" to "Fukuoka" to "Asia/Tokyo" to "+09:00",
        "札幌" to "Sapporo" to "Asia/Tokyo" to "+09:00",
        "广岛" to "Hiroshima" to "Asia/Tokyo" to "+09:00",
        "仙台" to "Sendai" to "Asia/Tokyo" to "+09:00",

        // 韩国（5个）
        "首尔" to "Seoul" to "Asia/Seoul" to "+09:00",
        "釜山" to "Busan" to "Asia/Seoul" to "+09:00",
        "仁川" to "Incheon" to "Asia/Seoul" to "+09:00",
        "大邱" to "Daegu" to "Asia/Seoul" to "+09:00",
        "大田" to "Daejeon" to "Asia/Seoul" to "+09:00",

        // 东南亚（30个）
        "新加坡" to "Singapore" to "Asia/Singapore" to "+08:00",
        "曼谷" to "Bangkok" to "Asia/Bangkok" to "+07:00",
        "清迈" to "Chiang Mai" to "Asia/Bangkok" to "+07:00",
        "普吉岛" to "Phuket" to "Asia/Bangkok" to "+07:00",
        "吉隆坡" to "Kuala Lumpur" to "Asia/Kuala_Lumpur" to "+08:00",
        "槟城" to "Penang" to "Asia/Kuala_Lumpur" to "+08:00",
        "新山" to "Johor Bahru" to "Asia/Kuala_Lumpur" to "+08:00",
        "雅加达" to "Jakarta" to "Asia/Jakarta" to "+07:00",
        "泗水" to "Surabaya" to "Asia/Jakarta" to "+07:00",
        "万隆" to "Bandung" to "Asia/Jakarta" to "+07:00",
        "巴厘岛" to "Bali" to "Asia/Makassar" to "+08:00",
        "马尼拉" to "Manila" to "Asia/Manila" to "+08:00",
        "宿务" to "Cebu" to "Asia/Manila" to "+08:00",
        "达沃" to "Davao" to "Asia/Manila" to "+08:00",
        "胡志明市" to "Ho Chi Minh City" to "Asia/Ho_Chi_Minh" to "+07:00",
        "金边" to "Phnom Penh" to "Asia/Phnom_Penh" to "+07:00",
        "暹粒" to "Siem Reap" to "Asia/Phnom_Penh" to "+07:00",
        "仰光" to "Yangon" to "Asia/Yangon" to "+06:30",
        "内比都" to "Naypyidaw" to "Asia/Yangon" to "+06:30",
        "加德满都" to "Kathmandu" to "Asia/Kathmandu" to "+05:45",
        "加尔各答" to "Kolkata" to "Asia/Kolkata" to "+05:30",
        "金奈" to "Chennai" to "Asia/Kolkata" to "+05:30",
        "海德拉巴" to "Hyderabad" to "Asia/Kolkata" to "+05:30",

        // 南亚/西亚（25个）
        "卡拉奇" to "Karachi" to "Asia/Karachi" to "+05:00",
        "拉合尔" to "Lahore" to "Asia/Karachi" to "+05:00",
        "伊斯兰堡" to "Islamabad" to "Asia/Karachi" to "+05:00",
        "迪拜" to "Dubai" to "Asia/Dubai" to "+04:00",
        "阿布扎比" to "Abu Dhabi" to "Asia/Dubai" to "+04:00",
        "沙迦" to "Sharjah" to "Asia/Dubai" to "+04:00",
        "利雅得" to "Riyadh" to "Asia/Riyadh" to "+03:00",
        "吉达" to "Jeddah" to "Asia/Riyadh" to "+03:00",
        "麦加" to "Mecca" to "Asia/Riyadh" to "+03:00",
        "德黑兰" to "Tehran" to "Asia/Tehran" to "+03:30",
        "伊斯法罕" to "Isfahan" to "Asia/Tehran" to "+03:30",
        "巴格达" to "Baghdad" to "Asia/Baghdad" to "+03:00",
        "巴士拉" to "Basra" to "Asia/Baghdad" to "+03:00",
        "科威特城" to "Kuwait City" to "Asia/Kuwait" to "+03:00",
        "麦纳麦" to "Manama" to "Asia/Bahrain" to "+03:00",
        "多哈" to "Doha" to "Asia/Qatar" to "+03:00",
        "安曼" to "Amman" to "Asia/Amman" to "+03:00",
        "贝鲁特" to "Beirut" to "Asia/Beirut" to "+02:00",
        "大马士革" to "Damascus" to "Asia/Damascus" to "+02:00",
        "耶路撒冷" to "Jerusalem" to "Asia/Jerusalem" to "+02:00",
        "特拉维夫" to "Tel Aviv" to "Asia/Jerusalem" to "+02:00",
        "利马索尔" to "Limassol" to "Asia/Nicosia" to "+02:00",
        "尼科西亚" to "Nicosia" to "Asia/Nicosia" to "+02:00",
        "喀布尔" to "Kabul" to "Asia/Kabul" to "+04:30",
        "坎大哈" to "Kandahar" to "Asia/Kabul" to "+04:30",

        // 中亚（10个）
        "塔什干" to "Tashkent" to "Asia/Tashkent" to "+05:00",
        "努尔苏丹" to "Nur-Sultan" to "Asia/Novosibirsk" to "+07:00",
        "阿拉木图" to "Almaty" to "Asia/Almaty" to "+05:00",
        "比什凯克" to "Bishkek" to "Asia/Bishkek" to "+06:00",
        "杜尚别" to "Dushanbe" to "Asia/Dushanbe" to "+05:00",
        "苦盏" to "Khujand" to "Asia/Dushanbe" to "+05:00",
        "阿什哈巴德" to "Ashgabat" to "Asia/Ashgabat" to "+05:00",
        "马什哈德" to "Mashhad" to "Asia/Tehran" to "+03:30",
        "伊斯坎德尔" to "Iskandar" to "Asia/Tashkent" to "+05:00",
        "撒马尔罕" to "Samarkand" to "Asia/Tashkent" to "+05:00",

        // 西亚（20个）
        "伊斯坦布尔" to "Istanbul" to "Europe/Istanbul" to "+03:00",
        "安卡拉" to "Ankara" to "Europe/Istanbul" to "+03:00",
        "伊兹密尔" to "Izmir" to "Europe/Istanbul" to "+03:00",
        "布尔萨" to "Bursa" to "Europe/Istanbul" to "+03:00",
        "安塔利亚" to "Antalya" to "Europe/Istanbul" to "+03:00",
        "加济安泰普" to "Gaziantep" to "Europe/Istanbul" to "+03:00",
        "贝伊奥卢" to "Beyoglu" to "Europe/Istanbul" to "+03:00",
        "梅尔辛" to "Mersin" to "Europe/Istanbul" to "+03:00",
        "阿达纳" to "Adana" to "Europe/Istanbul" to "+03:00",
        "科尼亚" to "Konya" to "Europe/Istanbul" to "+03:00",
        "吉布提市" to "Djibouti City" to "Africa/Djibouti" to "+03:00",
        "亚丁" to "Aden" to "Asia/Aden" to "+03:00",
        "萨那" to "Sana'a" to "Asia/Aden" to "+03:00",
        "马斯喀特" to "Muscat" to "Asia/Muscat" to "+04:00",
        "塞拉莱" to "Salalah" to "Asia/Muscat" to "+04:00",
        "迪拜沙迦" to "Sharjah" to "Asia/Dubai" to "+04:00",
        "富查伊拉" to "Fujairah" to "Asia/Dubai" to "+04:00",
        "阿治曼" to "Ajman" to "Asia/Dubai" to "+04:00",
        "乌姆盖万" to "Umm Al Quwain" to "Asia/Dubai" to "+04:00",
        "哈伊马角" to "Ras Al Khaimah" to "Asia/Dubai" to "+04:00",

        // 【欧洲：150个】
        // 西欧（40个）
        "伦敦" to "London" to "Europe/London" to "+00:00",
        "伯明翰" to "Birmingham" to "Europe/London" to "+00:00",
        "曼彻斯特" to "Manchester" to "Europe/London" to "+00:00",
        "利物浦" to "Liverpool" to "Europe/London" to "+00:00",
        "格拉斯哥" to "Glasgow" to "Europe/London" to "+00:00",
        "爱丁堡" to "Edinburgh" to "Europe/London" to "+00:00",
        "利兹" to "Leeds" to "Europe/London" to "+00:00",
        "纽卡斯尔" to "Newcastle" to "Europe/London" to "+00:00",
        "谢菲尔德" to "Sheffield" to "Europe/London" to "+00:00",
        "布里斯托尔" to "Bristol" to "Europe/London" to "+00:00",
        "巴黎" to "Paris" to "Europe/Paris" to "+01:00",
        "马赛" to "Marseille" to "Europe/Paris" to "+01:00",
        "里昂" to "Lyon" to "Europe/Paris" to "+01:00",
        "图卢兹" to "Toulouse" to "Europe/Paris" to "+01:00",
        "尼斯" to "Nice" to "Europe/Paris" to "+01:00",
        "南特" to "Nantes" to "Europe/Paris" to "+01:00",
        "斯特拉斯堡" to "Strasbourg" to "Europe/Paris" to "+01:00",
        "蒙彼利埃" to "Montpellier" to "Europe/Paris" to "+01:00",
        "波尔多" to "Bordeaux" to "Europe/Paris" to "+01:00",
        "里尔" to "Lille" to "Europe/Paris" to "+01:00",
        "柏林" to "Berlin" to "Europe/Berlin" to "+01:00",
        "慕尼黑" to "Munich" to "Europe/Berlin" to "+01:00",
        "汉堡" to "Hamburg" to "Europe/Berlin" to "+01:00",
        "法兰克福" to "Frankfurt" to "Europe/Berlin" to "+01:00",
        "科隆" to "Cologne" to "Europe/Berlin" to "+01:00",
        "杜塞尔多夫" to "Düsseldorf" to "Europe/Berlin" to "+01:00",
        "斯图加特" to "Stuttgart" to "Europe/Berlin" to "+01:00",
        "多特蒙德" to "Dortmund" to "Europe/Berlin" to "+01:00",
        "埃森" to "Essen" to "Europe/Berlin" to "+01:00",
        "不来梅" to "Bremen" to "Europe/Berlin" to "+01:00",
        "阿姆斯特丹" to "Amsterdam" to "Europe/Amsterdam" to "+01:00",
        "鹿特丹" to "Rotterdam" to "Europe/Amsterdam" to "+01:00",
        "海牙" to "The Hague" to "Europe/Amsterdam" to "+01:00",
        "乌得勒支" to "Utrecht" to "Europe/Amsterdam" to "+01:00",
        "埃因霍温" to "Eindhoven" to "Europe/Amsterdam" to "+01:00",
        "布鲁塞尔" to "Brussels" to "Europe/Brussels" to "+01:00",
        "安特卫普" to "Antwerp" to "Europe/Brussels" to "+01:00",
        "根特" to "Ghent" to "Europe/Brussels" to "+01:00",
        "沙勒罗瓦" to "Charleroi" to "Europe/Brussels" to "+01:00",
        "列日" to "Liège" to "Europe/Brussels" to "+01:00",

        // 南欧（40个）
        "罗马" to "Rome" to "Europe/Rome" to "+01:00",
        "米兰" to "Milan" to "Europe/Rome" to "+01:00",
        "那不勒斯" to "Naples" to "Europe/Rome" to "+01:00",
        "都灵" to "Turin" to "Europe/Rome" to "+01:00",
        "巴勒莫" to "Palermo" to "Europe/Rome" to "+01:00",
        "热那亚" to "Genoa" to "Europe/Rome" to "+01:00",
        "博洛尼亚" to "Bologna" to "Europe/Rome" to "+01:00",
        "佛罗伦萨" to "Florence" to "Europe/Rome" to "+01:00",
        "威尼斯" to "Venice" to "Europe/Rome" to "+01:00",
        "比萨" to "Pisa" to "Europe/Rome" to "+01:00",
        "马德里" to "Madrid" to "Europe/Madrid" to "+01:00",
        "巴塞罗那" to "Barcelona" to "Europe/Madrid" to "+01:00",
        "瓦伦西亚" to "Valencia" to "Europe/Madrid" to "+01:00",
        "塞维利亚" to "Seville" to "Europe/Madrid" to "+01:00",
        "马拉加" to "Malaga" to "Europe/Madrid" to "+01:00",
        "毕尔巴鄂" to "Bilbao" to "Europe/Madrid" to "+01:00",
        "萨拉戈萨" to "Zaragoza" to "Europe/Madrid" to "+01:00",
        "穆尔西亚" to "Murcia" to "Europe/Madrid" to "+01:00",
        "帕尔马" to "Palma" to "Europe/Madrid" to "+01:00",
        "格拉纳达" to "Granada" to "Europe/Madrid" to "+01:00",
        "里斯本" to "Lisbon" to "Europe/Lisbon" to "+00:00",
        "波尔图" to "Porto" to "Europe/Lisbon" to "+00:00",
        "布拉加" to "Braga" to "Europe/Lisbon" to "+00:00",
        "科英布拉" to "Coimbra" to "Europe/Lisbon" to "+00:00",
        "法鲁" to "Faro" to "Europe/Lisbon" to "+00:00",
        "雅典" to "Athens" to "Europe/Athens" to "+02:00",
        "塞萨洛尼基" to "Thessaloniki" to "Europe/Athens" to "+02:00",
        "帕特雷" to "Patras" to "Europe/Athens" to "+02:00",
        "伊拉克利翁" to "Heraklion" to "Europe/Athens" to "+02:00",
        "拉里萨" to "Larissa" to "Europe/Athens" to "+02:00",
        "布加勒斯特" to "Bucharest" to "Europe/Bucharest" to "+02:00",
        "雅西" to "Iasi" to "Europe/Bucharest" to "+02:00",
        "克卢日-纳波卡" to "Cluj-Napoca" to "Europe/Bucharest" to "+02:00",
        "蒂米什瓦拉" to "Timisoara" to "Europe/Bucharest" to "+02:00",
        "康斯坦察" to "Constanta" to "Europe/Bucharest" to "+02:00",
        "索非亚" to "Sofia" to "Europe/Sofia" to "+02:00",
        "普罗夫迪夫" to "Plovdiv" to "Europe/Sofia" to "+02:00",
        "瓦尔纳" to "Varna" to "Europe/Sofia" to "+02:00",
        "布尔加斯" to "Burgas" to "Europe/Sofia" to "+02:00",
        "斯科普里" to "Skopje" to "Europe/Skopje" to "+02:00",

        // 中欧/东欧（40个）
        "维也纳" to "Vienna" to "Europe/Vienna" to "+01:00",
        "格拉茨" to "Graz" to "Europe/Vienna" to "+01:00",
        "林茨" to "Linz" to "Europe/Vienna" to "+01:00",
        "萨尔茨堡" to "Salzburg" to "Europe/Vienna" to "+01:00",
        "因斯布鲁克" to "Innsbruck" to "Europe/Vienna" to "+01:00",
        "布拉格" to "Prague" to "Europe/Prague" to "+01:00",
        "布尔诺" to "Brno" to "Europe/Prague" to "+01:00",
        "奥洛穆茨" to "Olomouc" to "Europe/Prague" to "+01:00",
        "比尔森" to "Plzen" to "Europe/Prague" to "+01:00",
        "利贝雷茨" to "Liberec" to "Europe/Prague" to "+01:00",
        "华沙" to "Warsaw" to "Europe/Warsaw" to "+01:00",
        "克拉科夫" to "Krakow" to "Europe/Warsaw" to "+01:00",
        "罗兹" to "Lodz" to "Europe/Warsaw" to "+01:00",
        "弗罗茨瓦夫" to "Wroclaw" to "Europe/Warsaw" to "+01:00",
        "波兹南" to "Poznan" to "Europe/Warsaw" to "+01:00",
        "格但斯克" to "Gdansk" to "Europe/Warsaw" to "+01:00",
        "基辅" to "Kyiv" to "Europe/Kyiv" to "+02:00",
        "哈尔科夫" to "Kharkiv" to "Europe/Kyiv" to "+02:00",
        "敖德萨" to "Odesa" to "Europe/Kyiv" to "+02:00",
        "第聂伯罗" to "Dnipro" to "Europe/Kyiv" to "+02:00",
        "顿涅茨克" to "Donetsk" to "Europe/Kyiv" to "+02:00",
        "明斯克" to "Minsk" to "Europe/Minsk" to "+03:00",
        "戈梅利" to "Gomel" to "Europe/Minsk" to "+03:00",
        "莫吉廖夫" to "Mogilev" to "Europe/Minsk" to "+03:00",
        "维捷布斯克" to "Vitebsk" to "Europe/Minsk" to "+03:00",
        "布列斯特" to "Brest" to "Europe/Minsk" to "+03:00",
        "莫斯科" to "Moscow" to "Europe/Moscow" to "+03:00",
        "圣彼得堡" to "Saint Petersburg" to "Europe/Moscow" to "+03:00",
        "新西伯利亚" to "Novosibirsk" to "Asia/Novosibirsk" to "+07:00",
        "叶卡捷琳堡" to "Yekaterinburg" to "Asia/Yekaterinburg" to "+05:00",
        "下诺夫哥罗德" to "Nizhny Novgorod" to "Europe/Moscow" to "+03:00",
        "喀山" to "Kazan" to "Europe/Moscow" to "+03:00",
        "萨马拉" to "Samara" to "Europe/Samara" to "+04:00",
        "车里雅宾斯克" to "Chelyabinsk" to "Asia/Yekaterinburg" to "+05:00",
        "鄂木斯克" to "Omsk" to "Asia/Omsk" to "+06:00",
        "彼尔姆" to "Perm" to "Asia/Yekaterinburg" to "+05:00",
        "沃罗涅日" to "Voronezh" to "Europe/Moscow" to "+03:00",
        "伏尔加格勒" to "Volgograd" to "Europe/Moscow" to "+03:00",

        // 北欧（30个）
        "斯德哥尔摩" to "Stockholm" to "Europe/Stockholm" to "+01:00",
        "哥德堡" to "Gothenburg" to "Europe/Stockholm" to "+01:00",
        "马尔默" to "Malmö" to "Europe/Stockholm" to "+01:00",
        "乌普萨拉" to "Uppsala" to "Europe/Stockholm" to "+01:00",
        "林雪平" to "Linköping" to "Europe/Stockholm" to "+01:00",
        "奥斯陆" to "Oslo" to "Europe/Oslo" to "+01:00",
        "卑尔根" to "Bergen" to "Europe/Oslo" to "+01:00",
        "特隆赫姆" to "Trondheim" to "Europe/Oslo" to "+01:00",
        "斯塔万格" to "Stavanger" to "Europe/Oslo" to "+01:00",
        "克里斯蒂安桑" to "Kristiansand" to "Europe/Oslo" to "+01:00",
        "哥本哈根" to "Copenhagen" to "Europe/Copenhagen" to "+01:00",
        "奥胡斯" to "Aarhus" to "Europe/Copenhagen" to "+01:00",
        "欧登塞" to "Odense" to "Europe/Copenhagen" to "+01:00",
        "奥尔堡" to "Aalborg" to "Europe/Copenhagen" to "+01:00",
        "埃斯比约" to "Esbjerg" to "Europe/Copenhagen" to "+01:00",
        "赫尔辛基" to "Helsinki" to "Europe/Helsinki" to "+02:00",
        "坦佩雷" to "Tampere" to "Europe/Helsinki" to "+02:00",
        "图尔库" to "Turku" to "Europe/Helsinki" to "+02:00",
        "奥卢" to "Oulu" to "Europe/Helsinki" to "+02:00",
        "拉赫蒂" to "Lahti" to "Europe/Helsinki" to "+02:00",
        "雷克雅未克" to "Reykjavik" to "Atlantic/Reykjavik" to "+00:00",
        "阿克雷里" to "Akureyri" to "Atlantic/Reykjavik" to "+00:00",
        "伊萨菲厄泽" to "Ísafjörður" to "Atlantic/Reykjavik" to "+00:00",
        "博尔加内斯" to "Borgarnes" to "Atlantic/Reykjavik" to "+00:00",
        "哈布纳菲厄泽" to "Hafnarfjörður" to "Atlantic/Reykjavik" to "+00:00",
        "塔林" to "Tallinn" to "Europe/Tallinn" to "+02:00",
        "里加" to "Riga" to "Europe/Riga" to "+02:00",
        "维尔纽斯" to "Vilnius" to "Europe/Vilnius" to "+02:00",
        "塔尔图" to "Tartu" to "Europe/Tallinn" to "+02:00",
        "道加瓦皮尔斯" to "Daugavpils" to "Europe/Riga" to "+02:00",

        // 【美洲：120个】
        // 北美（60个）
        "纽约" to "New York" to "America/New_York" to "-04:00",
        "洛杉矶" to "Los Angeles" to "America/Los_Angeles" to "-07:00",
        "芝加哥" to "Chicago" to "America/Chicago" to "-05:00",
        "休斯顿" to "Houston" to "America/Chicago" to "-05:00",
        "费城" to "Philadelphia" to "America/New_York" to "-04:00",
        "菲尼克斯" to "Phoenix" to "America/Phoenix" to "-07:00",
        "圣安东尼奥" to "San Antonio" to "America/Chicago" to "-05:00",
        "圣地亚哥" to "San Diego" to "America/Los_Angeles" to "-07:00",
        "达拉斯" to "Dallas" to "America/Chicago" to "-05:00",
        "圣何塞" to "San Jose" to "America/Los_Angeles" to "-07:00",
        "奥斯汀" to "Austin" to "America/Chicago" to "-05:00",
        "杰克逊维尔" to "Jacksonville" to "America/New_York" to "-04:00",
        "旧金山" to "San Francisco" to "America/Los_Angeles" to "-07:00",
        "哥伦布" to "Columbus" to "America/New_York" to "-04:00",
        "印第安纳波利斯" to "Indianapolis" to "America/Indiana/Indianapolis" to "-04:00",
        "夏洛特" to "Charlotte" to "America/New_York" to "-04:00",
        "西雅图" to "Seattle" to "America/Los_Angeles" to "-07:00",
        "丹佛" to "Denver" to "America/Denver" to "-06:00",
        "华盛顿" to "Washington D.C." to "America/New_York" to "-04:00",
        "波士顿" to "Boston" to "America/New_York" to "-04:00",
        "迈阿密" to "Miami" to "America/New_York" to "-04:00",
        "亚特兰大" to "Atlanta" to "America/New_York" to "-04:00",
        "底特律" to "Detroit" to "America/New_York" to "-04:00",
        "明尼阿波利斯" to "Minneapolis" to "America/Chicago" to "-05:00",
        "巴尔的摩" to "Baltimore" to "America/New_York" to "-04:00",
        "波特兰" to "Portland" to "America/Los_Angeles" to "-07:00",
        "拉斯维加斯" to "Las Vegas" to "America/Los_Angeles" to "-07:00",
        "克利夫兰" to "Cleveland" to "America/New_York" to "-04:00",
        "辛辛那提" to "Cincinnati" to "America/New_York" to "-04:00",
        "多伦多" to "Toronto" to "America/Toronto" to "-04:00",
        "蒙特利尔" to "Montreal" to "America/Montreal" to "-04:00",
        "温哥华" to "Vancouver" to "America/Vancouver" to "-07:00",
        "渥太华" to "Ottawa" to "America/Toronto" to "-04:00",
        "卡尔加里" to "Calgary" to "America/Edmonton" to "-06:00",
        "埃德蒙顿" to "Edmonton" to "America/Edmonton" to "-06:00",
        "魁北克市" to "Quebec City" to "America/Montreal" to "-04:00",
        "温尼伯" to "Winnipeg" to "America/Winnipeg" to "-05:00",
        "汉密尔顿" to "Hamilton" to "America/Toronto" to "-04:00",
        "哈利法克斯" to "Halifax" to "America/Halifax" to "-03:00",
        "里贾纳" to "Regina" to "America/Regina" to "-06:00",
        "萨斯卡通" to "Saskatoon" to "America/Regina" to "-06:00",
        "圣约翰斯" to "St. John's" to "America/St_Johns" to "-02:30",
        "维多利亚" to "Victoria" to "America/Vancouver" to "-07:00",
        "基奇纳" to "Kitchener" to "America/Toronto" to "-04:00",
        "伦敦（加）" to "London (Canada)" to "America/Toronto" to "-04:00",
        "温莎" to "Windsor" to "America/Toronto" to "-04:00",
        "奥沙瓦" to "Oshawa" to "America/Toronto" to "-04:00",
        "巴里" to "Barrie" to "America/Toronto" to "-04:00",
        "金斯敦" to "Kingston" to "America/Toronto" to "-04:00",
        "圭尔夫" to "Guelph" to "America/Toronto" to "-04:00",
        "萨德伯里" to "Sudbury" to "America/Toronto" to "-04:00",
        "桑德贝" to "Thunder Bay" to "America/Winnipeg" to "-05:00",
        "夏洛特敦" to "Charlottetown" to "America/Halifax" to "-03:00",
        "弗雷德里克顿" to "Fredericton" to "America/Halifax" to "-03:00",
        "蒙克顿" to "Moncton" to "America/Halifax" to "-03:00",
        "密西沙加" to "Mississauga" to "America/Toronto" to "-04:00",

        // 南美（40个）
        "圣保罗" to "São Paulo" to "America/Sao_Paulo" to "-03:00",
        "里约热内卢" to "Rio de Janeiro" to "America/Sao_Paulo" to "-03:00",
        "巴西利亚" to "Brasilia" to "America/Sao_Paulo" to "-03:00",
        "贝洛奥里藏特" to "Belo Horizonte" to "America/Sao_Paulo" to "-03:00",
        "萨尔瓦多" to "Salvador" to "America/Bahia" to "-03:00",
        "福塔莱萨" to "Fortaleza" to "America/Fortaleza" to "-03:00",
        "库里蒂巴" to "Curitiba" to "America/Sao_Paulo" to "-03:00",
        "累西腓" to "Recife" to "America/Recife" to "-03:00",
        "马瑙斯" to "Manaus" to "America/Manaus" to "-04:00",
        "阿雷格里港" to "Porto Alegre" to "America/Sao_Paulo" to "-03:00",
        "布宜诺斯艾利斯" to "Buenos Aires" to "America/Argentina/Buenos_Aires" to "-03:00",
        "科尔多瓦" to "Cordoba" to "America/Argentina/Cordoba" to "-03:00",
        "罗萨里奥" to "Rosario" to "America/Argentina/Buenos_Aires" to "-03:00",
        "门多萨" to "Mendoza" to "America/Argentina/Mendoza" to "-03:00",
        "图库曼" to "Tucuman" to "America/Argentina/Tucuman" to "-03:00",
        "利马" to "Lima" to "America/Lima" to "-05:00",
        "库斯科" to "Cusco" to "America/Lima" to "-05:00",
        "阿雷基帕" to "Arequipa" to "America/Lima" to "-05:00",
        "特鲁希略" to "Trujillo" to "America/Lima" to "-05:00",
        "奇克拉约" to "Chiclayo" to "America/Lima" to "-05:00",
        "圣地亚哥" to "Santiago" to "America/Santiago" to "-03:00",
        "瓦尔帕莱索" to "Valparaiso" to "America/Santiago" to "-03:00",
        "康塞普西翁" to "Concepcion" to "America/Santiago" to "-03:00",
        "拉塞雷纳" to "La Serena" to "America/Santiago" to "-03:00",
        "安托法加斯塔" to "Antofagasta" to "America/Santiago" to "-03:00",
        "波哥大" to "Bogota" to "America/Bogota" to "-05:00",
        "麦德林" to "Medellin" to "America/Bogota" to "-05:00",
        "卡利" to "Cali" to "America/Bogota" to "-05:00",
        "巴兰基亚" to "Barranquilla" to "America/Bogota" to "-05:00",
        "卡塔赫纳" to "Cartagena" to "America/Bogota" to "-05:00",
        "加拉加斯" to "Caracas" to "America/Caracas" to "-04:00",
        "马拉开波" to "Maracaibo" to "America/Caracas" to "-04:00",
        "巴伦西亚" to "Valencia" to "America/Caracas" to "-04:00",
        "基多" to "Quito" to "America/Guayaquil" to "-05:00",
        "瓜亚基尔" to "Guayaquil" to "America/Guayaquil" to "-05:00",
        "昆卡" to "Cuenca" to "America/Guayaquil" to "-05:00",
        "拉巴斯" to "La Paz" to "America/La_Paz" to "-04:00",
        "苏克雷" to "Sucre" to "America/La_Paz" to "-04:00",
        "圣克鲁斯" to "Santa Cruz" to "America/La_Paz" to "-04:00",

        // 中美/加勒比（20个）
        "墨西哥城" to "Mexico City" to "America/Mexico_City" to "-05:00",
        "瓜达拉哈拉" to "Guadalajara" to "America/Mexico_City" to "-05:00",
        "蒙特雷" to "Monterrey" to "America/Mexico_City" to "-05:00",
        "普埃布拉" to "Puebla" to "America/Mexico_City" to "-05:00",
        "蒂华纳" to "Tijuana" to "America/Tijuana" to "-07:00",
        "巴拿马城" to "Panama City" to "America/Panama" to "-05:00",
        "圣何塞（哥）" to "San Jose (Costa Rica)" to "America/Costa_Rica" to "-06:00",
        "危地马拉城" to "Guatemala City" to "America/Guatemala" to "-06:00",
        "特古西加尔巴" to "Tegucigalpa" to "America/Tegucigalpa" to "-06:00",
        "马那瓜" to "Managua" to "America/Managua" to "-06:00",
        "圣萨尔瓦多" to "San Salvador" to "America/El_Salvador" to "-06:00",
        "太子港" to "Port-au-Prince" to "America/Port-au-Prince" to "-04:00",
        "金斯敦" to "Kingston" to "America/Jamaica" to "-05:00",
        "哈瓦那" to "Havana" to "America/Havana" to "-04:00",
        "圣地亚哥（古）" to "Santiago (Cuba)" to "America/Havana" to "-04:00",
        "圣多明各" to "Santo Domingo" to "America/Santo_Domingo" to "-04:00",
        "拿骚" to "Nassau" to "America/Nassau" to "-04:00",
        "乔治敦" to "Georgetown" to "America/Guyana" to "-04:00",
        "西班牙港" to "Port of Spain" to "America/Port_of_Spain" to "-04:00",
        "金斯敦（牙）" to "Kingston (Jamaica)" to "America/Jamaica" to "-05:00",

        // 【非洲：30个】
        "开罗" to "Cairo" to "Africa/Cairo" to "+02:00",
        "亚历山大" to "Alexandria" to "Africa/Cairo" to "+02:00",
        "吉萨" to "Giza" to "Africa/Cairo" to "+02:00",
        "卢克索" to "Luxor" to "Africa/Cairo" to "+02:00",
        "阿斯旺" to "Aswan" to "Africa/Cairo" to "+02:00",
        "约翰内斯堡" to "Johannesburg" to "Africa/Johannesburg" to "+02:00",
        "开普敦" to "Cape Town" to "Africa/Johannesburg" to "+02:00",
        "德班" to "Durban" to "Africa/Johannesburg" to "+02:00",
        "比勒陀利亚" to "Pretoria" to "Africa/Johannesburg" to "+02:00",
        "伊丽莎白港" to "Port Elizabeth" to "Africa/Johannesburg" to "+02:00",
        "拉各斯" to "Lagos" to "Africa/Lagos" to "+01:00",
        "卡诺" to "Kano" to "Africa/Lagos" to "+01:00",
        "伊巴丹" to "Ibadan" to "Africa/Lagos" to "+01:00",
        "阿布贾" to "Abuja" to "Africa/Lagos" to "+01:00",
        "坎帕拉" to "Kampala" to "Africa/Kampala" to "+03:00",
        "内罗毕" to "Nairobi" to "Africa/Nairobi" to "+03:00",
        "蒙巴萨" to "Mombasa" to "Africa/Nairobi" to "+03:00",
        "达累斯萨拉姆" to "Dar es Salaam" to "Africa/Dar_es_Salaam" to "+03:00",
        "坦噶" to "Tanga" to "Africa/Dar_es_Salaam" to "+03:00",
        "阿尔及尔" to "Algiers" to "Africa/Algiers" to "+01:00",
        "奥兰" to "Oran" to "Africa/Algiers" to "+01:00",
        "君士坦丁" to "Constantine" to "Africa/Algiers" to "+01:00",
        "卡萨布兰卡" to "Casablanca" to "Africa/Casablanca" to "+00:00",
        "拉巴特" to "Rabat" to "Africa/Casablanca" to "+00:00",
        "马拉喀什" to "Marrakech" to "Africa/Casablanca" to "+00:00",
        "突尼斯市" to "Tunis" to "Africa/Tunis" to "+01:00",
        "苏塞" to "Sousse" to "Africa/Tunis" to "+01:00",
        "斯法克斯" to "Sfax" to "Africa/Tunis" to "+01:00",
        "阿克拉" to "Accra" to "Africa/Accra" to "+00:00",
        "库马西" to "Kumasi" to "Africa/Accra" to "+00:00",

        // 【大洋洲：20个】
        "悉尼" to "Sydney" to "Australia/Sydney" to "+11:00",
        "墨尔本" to "Melbourne" to "Australia/Melbourne" to "+11:00",
        "布里斯班" to "Brisbane" to "Australia/Brisbane" to "+10:00",
        "珀斯" to "Perth" to "Australia/Perth" to "+08:00",
        "阿德莱德" to "Adelaide" to "Australia/Adelaide" to "+10:30",
        "黄金海岸" to "Gold Coast" to "Australia/Brisbane" to "+10:00",
        "纽卡斯尔" to "Newcastle" to "Australia/Sydney" to "+11:00",
        "堪培拉" to "Canberra" to "Australia/Canberra" to "+11:00",
        "霍巴特" to "Hobart" to "Australia/Hobart" to "+11:00",
        "达尔文" to "Darwin" to "Australia/Darwin" to "+09:30",
        "奥克兰" to "Auckland" to "Pacific/Auckland" to "+13:00",
        "惠灵顿" to "Wellington" to "Pacific/Auckland" to "+13:00",
        "基督城" to "Christchurch" to "Pacific/Auckland" to "+13:00",
        "克赖斯特彻奇" to "Christchurch" to "Pacific/Auckland" to "+13:00",
        "达尼丁" to "Dunedin" to "Pacific/Auckland" to "+13:00",
        "斐济苏瓦" to "Suva (Fiji)" to "Pacific/Fiji" to "+12:00",
        "巴布亚新几内亚莫尔兹比港" to "Port Moresby (PNG)" to "Pacific/Port_Moresby" to "+10:00",
        "所罗门群岛霍尼亚拉" to "Honiara (Solomon Islands)" to "Pacific/Guadalcanal" to "+11:00",
        "瓦努阿图维拉港" to "Port Vila (Vanuatu)" to "Pacific/Efate" to "+11:00",
        "萨摩亚阿皮亚" to "Apia (Samoa)" to "Pacific/Apia" to "+13:00"
    )

    /**
     * 生成500个热门城市的精准世界时钟数据
     */
    fun generateAccurate500WorldClocks(): List<WorldClockEntity> {
        return HOT_CITIES.map { entry ->
            val zoneId = entry.first.second
            val cityChName = entry.first.first.first
            val cityEnName = entry.first.first.second
            val timeOffsetStr = entry.second
            WorldClockEntity(
                cityName = cityChName,
                cityEnglishName = cityEnName,
                zoneId = zoneId,
                timeOffset = timeOffsetStr,
                currentTimeMills = 0,
                dayStatus = 0,
                selectedTime = -1
            )
        }.sortedBy {
            it.cityEnglishName.trim().uppercase().first()
        }
    }
}